plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.3'
	id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'
configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}
repositories {
	mavenCentral()
}




dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'
	implementation 'org.jsoup:jsoup:1.17.2'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	implementation group: 'org.bgee.log4jdbc-log4j2', name: 'log4jdbc-log4j2-jdbc4.1', version: '1.16'

	implementation 'jakarta.servlet:jakarta.servlet-api:5.0.0'

	implementation group: 'org.jxls', name: 'jxls', version: '2.4.2'

	implementation group: 'com.googlecode.json-simple', name:'json-simple',version:'1.1'
	implementation 'org.json:json:20231013'

	implementation group: 'com.google.code.gson', name: 'gson', version: '2.9.1'
	implementation fileTree(dir: 'libs', include: ['*.jar'])
	implementation 'com.github.ulisesbocchio:jasypt-spring-boot-starter:2.1.0'
	implementation 'org.mariadb.jdbc:mariadb-java-client:2.2.1'
	implementation 'javax.xml.bind:jaxb-api:2.2.4'
	implementation 'com.google.guava:guava:33.0.0-jre'
	implementation 'org.springframework.boot:spring-boot-starter-aop'

	implementation 'org.springframework.boot:spring-boot-starter-websocket'
	compileOnly 'org.projectlombok:lombok:1.18.26'
	annotationProcessor 'org.projectlombok:lombok:1.18.26'

	implementation("io.jsonwebtoken:jjwt-api:0.11.5")
	implementation("io.jsonwebtoken:jjwt-impl:0.11.5")
	implementation("io.jsonwebtoken:jjwt-jackson:0.11.5")
	implementation platform("io.awspring.cloud:spring-cloud-aws-dependencies:3.0.1")
	implementation 'io.awspring.cloud:spring-cloud-aws-starter-sqs'
	implementation group: 'commons-codec', name: 'commons-codec', version: '1.18.0'
	implementation 'com.github.shyiko:mysql-binlog-connector-java:0.21.0'


}
