spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:mysql://192.168.0.101:3306/testDB?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.hikari.username=test
spring.datasource.hikari.password=test
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.max-lifetime=58000
spring.datasource.hikari.connection-test-query=SELECT 1

binlogClient.enabled=false
sqsSubscriber.enabled=false